version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: authcore_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authcore
    ports:
      - "5432:5432"
    volumes:
      - authcore_postgres_data:/var/lib/postgresql/data
volumes:
  authcore_postgres_data:
